Attach("X1_N_equations.m");
Attach("low_degree_places.m");
import "X1_N_equations.m" : equations;
Attach("assorted_functions.m");
import "assorted_functions.m" : Main2;
if assigned N then;
    N_int:=StringToInteger(N);
    if assigned d then;
        d_int := StringToInteger(d);
        cusp_sigs,candidates :=  Main2(N_int : d:=d_int, write_results_to_file := true);
    else;
        cusp_sigs,candidates :=  Main2(N_int : write_results_to_file := true);
    end if;
    PrintFile("data/cusp_signatures_" cat N, cusp_sigs : Overwrite:=true);
    PrintFile("data/candidates_" cat N, candidates : Overwrite:=true);
end if;
